### ISSUE TITLE
Is the 04d46c7 revision of the library available under BSD?

### ISSUE THREAD

**Issue by RnbwNoise** [jameswalmsley/FullFAT#6]
There was a commit that changed the license from GPL to BSD: https://github.com/jameswalmsley/FullFAT/commit/04d46c717a2e69634325ee810223447be1854837 but it seems that it got detached from the master branch. Was the commit made by an accident or this version of library is actually available under the terms of the BSD licence?

**Comment by jameswalmsley** [comment]
Thats not meant to be a public commit, and the library is under GPL.
See FreeRTOS +FAT for the latest version.
