### ISSUE TITLE
FAT check is too strict for FAT12

### ISSUE THREAD

**Issue by lazyhamster** [jameswalmsley/FullFAT#7]
In function "FF_DetermineFatType" when checking FAT12 you compare first byte (which is FATID) to 0xF8. This check is good for FAT formatted partitions but prevents from reading some floppy images. 

According to Wikipedia FATID value can be either 0xF0 or in [0xF8-0xFF] range.

I have some image files formatted in FAT12 with different values in FATID from accepted range. They can be read by FullFAT without any problems after modifying check function.

Did you specifically restricted library to work only on partitioned disks or is it ok to extend check range?

**Comment by jameswalmsley** [comment]
Hi,

It would be fine to update the fat-check.
I would suggest you look at FreeRTOS +FAT, the library is actually my FullFAT code but updated and maintained to the FreeRTOS coding standards.

Their latest code is really really good, and fixes some long-standing issue with FullFAT. Maybe you might find that the FAT12 check is fixed.

I'll forward this information to hein tibosch who is the guy who's really maintaining it now.

Thanks for your patience in using this, I haven't checked on FullFAT for a long time.

J

**Comment by lazyhamster** [comment]
Hi. Thanks for the response.
I've briefly looked at FreeRTOS +FAT code and it seems that they have the same restriction for FAT12.

**Comment by jameswalmsley** [comment]
Hi,

Thanks for the information, I'll pass this on to Hein, and I'm pretty sure he'll have a patch very quickly.

J
